### ISSUE TITLE
Translation error in paw position x

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblvideo#4]
Looking at the data for `2019-08-04_002_ibl_witten_04` the paw positions are misaligned with the raw video.  Here's an example:

![12507](https://user-images.githubusercontent.com/25670666/64279024-cc1b7780-cf56-11e9-8086-e443e32f2908.png)

**Comment by oliche** [comment]
Hey Miles:
1) it this throughout the whole video ?
2) is this for all the sessions or only this one ?

**Comment by k1o0** [comment]
It's throughout the video.  @mschart believes it is from restitching the video fragments.  Perhaps the cropping goes outside of the frame.  The nostril and eye positions are correct.   I haven't check any other sessions yet.

**Comment by k1o0** [comment]
For ZM_1035 and the other ibl_witten session the coordinates are aligned

**Comment by juhuntenburg** [comment]
I believe this is outdated as paw tracking has been improved. Closing for now, feel free to reopen if necessary
